# Created using wingetcreate

PackageIdentifier: Amazon.WorkSpacesClient
PackageVersion: 3.1.8.2150
PackageLocale: en-US
Publisher: Amazon Web Services, Inc
PackageName: Amazon WorkSpaces Client
ShortDescription: Amazon WorkSpaces Client for Windows 
ManifestType: defaultLocale
ManifestVersion: 1.0.0
